<?php

namespace PhpSatuSehat\FHIR;

class ObservationCategory extends Base {
  public const SOCIAL_HISTORY = [
    'code' => 'social-history',
    'display' => 'Social History',
    'definition' => "Social History Observations define the patient's occupational, personal (e.g., lifestyle), social, familial, and environmental history and health risk factors that may impact the patient's health.",
  ];

  public const VITAL_SIGNS = [
    'code' => 'vital-signs',
    'display' => 'Vital Signs',
    'definition' => "Clinical observations measure the body's basic functions such as blood pressure, heart rate, respiratory rate, height, weight, body mass index, head circumference, pulse oximetry, temperature, and body surface area.",
  ];

  public const IMAGING = [
    'code' => 'imaging',
    'display' => 'Imaging',
    'definition' => "Imaging Observations measure the images generated by medical imaging modalities such as digital X-ray, ultrasound, CT, MRI, and ultrasound observations.",
  ];

  public const LABORATORY = [
    'code' => 'laboratory',
    'display' => 'Laboratory',
    'definition' => "Laboratory Observations measure the results of analyses performed by laboratories.",
  ];

  public const PROCEDURE = [
    'code' => 'procedure',
    'display' => 'Procedure',
    'definition' => "Procedure Observations measure the results of clinical investigations performed on the patient.",
  ];

  public const SURVEY = [
    'code' => 'survey',
    'display' => 'Survey',
    'definition' => "Survey Observations measure the results of surveys.",
  ];

  public const EXAM = [
    'code' => 'exam',
    'display' => 'Exam',
    'definition' => "Exam Observations measure the results of physical exams.",
  ];

  public const THERAPY = [
    'code' => 'therapy',
    'display' => 'Therapy',
    'definition' => "Therapy Observations measure the results of treatments.",
  ];

  public static function values(): array {
    return [
      self::SOCIAL_HISTORY['code'] => self::SOCIAL_HISTORY,
      self::VITAL_SIGNS['code'] => self::VITAL_SIGNS,
      self::IMAGING['code'] => self::IMAGING,
      self::LABORATORY['code'] => self::LABORATORY,
      self::PROCEDURE['code'] => self::PROCEDURE,
      self::SURVEY['code'] => self::SURVEY,
      self::EXAM['code'] => self::EXAM,
      self::THERAPY['code'] => self::THERAPY
    ];
  }
}